#!/usr/bin/env osascript
# Returns the current playing song in Spotify for OSX

tell application "Spotify"
  if it is running then
    if player state is playing then
      set track_name to name of current track
      set artist_name to artist of current track

      "#[fg=colour41,nobold]#[fg=colour16, bg=colour41, nobold] " & artist_name & " - " & track_name & " #[bg=colour41]"
    end if
  end if
end tell
