#!/usr/bin/env bash

declare -a extensions=("alexkrechik.cucumberautocomplete"
                       "aws-scripting-guy.cform"
                       "azemoh.one-monokai"
                       "bencoleman.armview"
                       "borkdude.clj-kondo"
                       "bungcip.better-toml"
                       "dbaeumer.vscode-eslint"
                       "eamodio.gitlens"
                       "EditorConfig.EditorConfig"
                       "Equinusocio.vsc-community-material-theme"
                       "Equinusocio.vsc-material-theme"
                       "equinusocio.vsc-material-theme-icons"
                       "golang.go"
                       "hashicorp.terraform"
                       "johnpapa.vscode-peacock"
                       "k--kato.intellij-idea-keybindings"
                       "karigari.chat"
                       "kddejong.vscode-cfn-lint"
                       "maelvalais.autoconf"
                       "mechatroner.rainbow-csv"
                       "ms-python.python"
                       "ms-python.vscode-pylance"
                       "ms-vscode.vscode-typescript-tslint-plugin"
                       "ms-vsliveshare.vsliveshare"
                       "ms-vsliveshare.vsliveshare-audio"
                       "ms-vsliveshare.vsliveshare-pack"
                       "pjmiravalle.terraform-advanced-syntax-highlighting"
                       "redhat.vscode-commons"
                       "redhat.vscode-yaml"
                       "sldobri.daily"
                       "trinm1709.dracula-theme-from-intellij"
                       "VisualStudioExptTeam.vscodeintellicode"
                       "vscode-icons-team.vscode-icons"
                       "wwm.better-align"
                       "zhuangtongfa.material-theme"
                       )

for ext in "${extensions[@]}"
do
    code --install-extension "$ext"
done